### PR TITLE
update frame-metadata to new crate + cargo update

### PR DESCRIPTION
**Pull request by haerdib**

### CODE REVIEW

**Review by brenzi — APPROVED** [review]
I don't like hardcoding v13, but I guess we can lift that and become generic again once we upgrade beyond v14?

**Comment by clangenb** [comment]
I am not certain if we can un-hardcode the metadata version. Before, substrate had only one version marked as valid and the rest as deprecated in the rust code. I don't believe they have changed that now.

**Review by clangenb — APPROVED** [review]
Cool. Looks good to me.

**Comment by haerdib** [comment]
> 
> 
> I don't like hardcoding v13, but I guess we can lift that and become generic again once we upgrade beyond v14?

Yes - by default the newest version will be taken (see reexport : https://github.com/paritytech/frame-metadata/blob/main/frame-metadata/src/lib.rs#L49-L53) . So if we upgrade so v14 we will be able to remove the v- specification.

**Pull request merged**
