### PR TITLE
Version update e5437e

### PR DESCRIPTION
**Pull request by haerdib**
Do not remove this PR/branch. Currently in use by ternoa keyvault : https://github.com/capsule-corp-ternoa/sgx-keyvault

### CODE REVIEW

**Comment by clangenb** [comment]
Why do we not want to have this in master?

**Comment by haerdib** [comment]
Our worker has never been on this substrate commit. This was made to match the node version of ternoa.

**Comment by clangenb** [comment]
What's the state of ternoa here? If they don't intend to upgrade, they should fork the api-client, instead of having us keep that branch.

**Comment by brenzi** [comment]
agreed. We will remove this as soon as we have confirmation of the fork

**Comment by haerdib** [comment]
I'm closing this for now, it's been open for long enough.

**Pull request closed without merging**
