### PR TITLE
Add a new function storage_double_map_key_prefix to meta 

### PR DESCRIPTION
**Pull request by bai-3**
use as this
```
let key = api
    .get_storage_double_map_key_prefix("WeteeGov", "ReferendumInfoOf", 5000)
    .unwrap();

let storage_keys = api
    .get_storage_keys_paged(Some(key), 10, None, None)
    .unwrap();

for storage_key in storage_keys.iter() {
    println!("Retrieving value for key {:?}", storage_key);
    let storage_data: ReferendumInfo<BlockNumber, RuntimeCall, Balance> = api
        .get_storage_by_key_hash(storage_key.clone(), None)
        .unwrap()
        .unwrap();
    println!("Retrieved data {:?}", storage_data);
}
```

I have add test to example

### CODE REVIEW

**Comment by bai-3** [comment]
There was a little problem with GitHub. My new commits were not updated to the PR. So I restarted a PR

**Review by haerdib — COMMENTED** [review]
Awesome, thanks a lot for adding the example 🥳 

One thing: Could you fix the clippy warning? CI will only then run the example (see https://github.com/scs/substrate-api-client/actions/runs/4739712591/jobs/8415556988?pr=542)

**Comment by bai-3** [comment]
@haerdib I have fixed the clippy warning

**Comment by haerdib** [comment]
Thanks a lot! There seem to be merge conflicts now. Would it be possible to rebase your branch?

**Pull request closed without merging**
