### PR TITLE
Cl update to 6ae3b6c4ddc03d4cdb10bd1d417b95d20f4c1b6e

### PR DESCRIPTION
**Pull request by clangenb**
* Bump substrate to bump version to 8700dbb1858f01b6ea6e3fc5d40d1478e7634c60
* Updated Extrinsic to V4
* No longer depend on local primitives crate, which is now deleted
* GenericAddress now uses substrate node_primives' types: GenericAddress = Address<AccountIndex, AccountId>

### CODE REVIEW

**Comment by brenzi** [comment]
why does the name of your branch not correspond to the upstream rev you selected? Please make sure the merge message contains the correct rev in the end...

**Comment by brenzi** [comment]
You're mixing `'` and `"` in toml. let's just use `"` plz.

**Comment by brenzi** [comment]
I could fix the issue, but unfortunately we need another upstream patch. I will file another PR but I suggest we do the whole upstream port against scsfork for now.
https://github.com/scs/substrate/tree/brenzi-fix-full-crypto

**Comment by brenzi** [comment]
Here's that PR: https://github.com/paritytech/substrate/pull/4133

**Comment by clangenb** [comment]
closed in favor of https://github.com/scs/substrate-api-client/tree/cl-update-to-3bf9540e72df5ecb3955845764dfee7dcdbb26b5

**Pull request closed without merging**
