### PR TITLE
Add function `get_system_account_next_index`

### LINKED ISSUE #572: Support system_accountNextIndex RPC
We currently have an [issue ](https://github.com/litentry/litentry-parachain/issues/1425) regarding `accountNextIndex` and the system API [link ](https://polkadot.js.org/docs/kusama/rpc/#accountnextindexaccountid-accountid-index) is provided here. We are currently using substrate-api-client with polkadot-v0.9.39-tag-v0.7.0, which does not have the `system_accountNextIndex` RPC. So, I would like to ask, do you have any plans to include this RPC in which version? Thank you!

### PR DESCRIPTION
**Pull request by haerdib**
Fixes #572

Regarding the `// FIXME: Remove once #391 is fixed.` : Issue added in #574

### CODE REVIEW

**Review by echevrier — APPROVED** [review]
LGTM

**Review by Niederb — APPROVED** [review]
👍

**Comment by Kailai-Wang** [comment]
Thanks @haerdib - this helps us too! 🚀

**Comment by Kailai-Wang** [comment]
Btw would it be possbile to backport it to `polkadot-v0.9.39` branch? The worker is still based on that branch :)

**Comment by haerdib** [comment]
Sure, I don't think that should be a problem. Let me try that.

**Comment by haerdib** [comment]
Added here: https://github.com/scs/substrate-api-client/commit/d872c2ca4328a30222e4d470c8fc4921abad9f34

**Pull request merged**
