### PR TITLE
Add instantiate_with_code

### PR DESCRIPTION
**Pull request by netrikare**
I added support for `instantiate_with_code` contracts API call + example usage.

### CODE REVIEW

**Review by clangenb — COMMENTED** [review]
Thank you very much for your contribution.

It looks good. However, could you make a remark in the example that it is community maintained and not CI tested; therefore it may not work as is? Could you also to the `extrinsic/contract` module that it is community maintained?

We won't integrate it in the CI, as we found out in the past that the effort is too big to maintain a custom node.

If you add these two things, I am happy to merge.

**Comment by netrikare** [comment]
I added the message.

On a side note: I see you are testing against minimal `node-template` instead of `node`, which has all the default pallets built in. Maybe instead of building node-template in your CI you could simply pull `parity/substrate` docker image and test against it? No maintenance cost then.

**Comment by clangenb** [comment]
I have only found a substrate docker node with a very old substrate version. All still v3.0.0, do you know a docker source with a recent substrate version? I would be very happy to use that.

**Comment by netrikare** [comment]
Comparing commit hashes, it looks like `parity/substrate:latest` image tracks master branch.

**Comment by clangenb** [comment]
Ok, cool. Thanks for the info. I will change that sometimes soon. 👍 

* #204

**Review by clangenb — APPROVED** [review]
Thx!

**Pull request merged**
